PREFIX ex: <http://example.org/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> SELECT ?p ?n ?a ?s WHERE { ?p foaf:name ?n ; foaf:age ?a ; ex:salary ?s FILTER(CONTAINS(?n, "Grace Hopper 7")) }