PREFIX ex: <http://example.org/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> SELECT ?d ?t ?y WHERE { ?d ex:title ?t ; ex:year ?y FILTER(LANGMATCHES(LANG(?t), "en")) }