PREFIX ex: <http://example.org/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> SELECT ?p ?a WHERE { ?p foaf:age ?a ; ex:worksFor ?o FILTER(REGEX(STR(?p), "person/1[0-9]{3}$")) }