<script lang="ts">
  // The explanation beside the plan tree (C18 §6.6.6): what the query asks and the notes
  // on its operators, each linked to its node. A link selects the node in the tree, and
  // hovering a node in the tree highlights the sentences and notes that cite it.
  import type { ExplainNote, ExplainSentence, Explanation, NodeFacts } from '$lib/explain';
  import { cites } from '$lib/explain';

  let {
    explanation = null,
    notes = [],
    nodes = [],
    shownNotes = 12,
    executed = true,
    stopped = false,
    loading = false,
    error = null,
    hovered = null,
    onselect,
    onlight,
  }: {
    explanation?: Explanation | null;
    notes?: ExplainNote[];
    nodes?: NodeFacts[];
    shownNotes?: number;
    executed?: boolean;
    /** A budget stopped the query: the notes say why it is slow. */
    stopped?: boolean;
    loading?: boolean;
    error?: string | null;
    /** The node hovered in the tree. */
    hovered?: string | null;
    onselect?: (id: string) => void;
    /** The nodes a hovered sentence cites, or null. */
    onlight?: (ids: string[] | null) => void;
  } = $props();

  let showTemplate = $state(false);
  let more = $state(false);

  const byId = $derived(new Map(nodes.map((n) => [n.id, n])));
  const label = (id: string) => byId.get(id)?.operator ?? id;
  const generated = $derived(explanation?.source === 'model' && !showTemplate);
  const asks = $derived<ExplainSentence[]>(
    explanation
      ? showTemplate && explanation.template
        ? explanation.template.asks
        : explanation.asks
      : [],
  );
  // the model's notes replace the deterministic ones only while its text is shown
  const shown = $derived<ExplainNote[]>(
    explanation && explanation.source === 'model' && !showTemplate ? explanation.notes : notes,
  );
  const visible = $derived(more ? shown : shown.slice(0, shownNotes));
  const nodeNotes = $derived(visible.filter((n) => n.node));
  const queryNotes = $derived(visible.filter((n) => !n.node));
  const MARK = { high: '●', warning: '⚠', info: 'ⓘ' } as const;
</script>

<aside class="panel" aria-label="Explanation">
  {#if error}
    <p class="error">{error}</p>
  {/if}
  <section aria-label="What it asks">
    <h3>What it asks</h3>
    {#if asks.length}
      <p class="asks" class:generated>
        {#each asks as s, i (i)}
          <span
            class="sentence"
            class:lit={hovered != null && cites(s, hovered)}
            role="note"
            onmouseenter={() => onlight?.(s.nodes)}
            onmouseleave={() => onlight?.(null)}
            >{s.text}
            {#each s.nodes as id (id)}<button
                class="link"
                onclick={() => onselect?.(id)}
                title="Node {id}">‹{label(id)}›</button
              >{' '}{/each}</span
          >{' '}
        {/each}
      </p>
    {:else if loading}
      <p class="faint"><span class="spinner"></span> Reading the plan…</p>
    {/if}
    {#if !executed}<p class="faint">The figures are the planner's estimates.</p>{/if}
  </section>

  {#if shown.length}
    <section aria-label={stopped ? 'Why it is slow' : 'Notes'}>
      <h3>{stopped ? 'Why it is slow' : 'Notes'}</h3>
      <ul class="notes">
        {#each queryNotes as n, i (i)}
          <li class="note {n.severity}">
            <span class="mark" aria-label={n.severity}>{MARK[n.severity]}</span>
            <span
              >{n.text}{#if n.range}
                <span class="faint">(line {n.range.line})</span>{/if}</span
            >
          </li>
        {/each}
        {#each nodeNotes as n, i (i)}
          <li class="note {n.severity}" class:lit={hovered != null && cites(n, hovered)}>
            <span class="mark" aria-label={n.severity}>{MARK[n.severity]}</span>
            <span
              >{n.text}
              <button class="link" onclick={() => onselect?.(n.node!)} title="Node {n.node}"
                >‹{label(n.node!)}›</button
              ></span
            >
          </li>
        {/each}
      </ul>
      {#if shown.length > shownNotes}
        <button class="btn sm ghost" onclick={() => (more = !more)}
          >{more ? 'Fewer' : `More (${shown.length - shownNotes})`}</button
        >
      {/if}
    </section>
  {/if}

  {#if explanation?.source === 'model'}
    <footer class="faint">
      {#if generated}
        Generated by {explanation.provider} · {explanation.model}, checked against the plan.
      {:else}
        Written from templates.
      {/if}
      <button class="btn sm ghost" onclick={() => (showTemplate = !showTemplate)}
        >{showTemplate ? 'Show generated text' : 'Show template text'}</button
      >
    </footer>
  {/if}
</aside>

<style>
  .panel {
    display: flex;
    flex-direction: column;
    gap: 14px;
    padding: 12px 14px;
    overflow: auto;
    min-height: 0;
    font-size: var(--fs);
    line-height: 1.5;
  }
  h3 {
    margin: 0 0 4px;
    font-size: var(--fs-sm);
    font-weight: 600;
    color: var(--text-2);
  }
  p {
    margin: 0;
  }
  .asks.generated {
    font-style: italic;
  }
  .sentence.lit,
  .note.lit {
    background: color-mix(in srgb, var(--iri) 16%, transparent);
    border-radius: 3px;
  }
  .link {
    all: unset;
    cursor: pointer;
    color: var(--iri);
    font-size: var(--fs-sm);
    white-space: nowrap;
  }
  .link:hover,
  .link:focus-visible {
    text-decoration: underline;
  }
  .notes {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .note {
    display: flex;
    gap: 6px;
    align-items: baseline;
  }
  .mark {
    flex: none;
    width: 1em;
    text-align: center;
  }
  .note.high .mark {
    color: var(--danger);
  }
  .note.warning .mark {
    color: var(--warn, var(--spark));
  }
  .note.info .mark {
    color: var(--text-3);
  }
  .error {
    color: var(--danger);
  }
  footer {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    font-size: var(--fs-sm);
  }
</style>
