"""Sparkles: an embedded RDF database with SPARQL 1.2, reasoning and SHACL and ShEx
validation.

>>> from sparkles import Dataset, NamedNode, Literal, Quad
>>> ds = Dataset()
>>> ds.load('<http://ex.org/a> <http://ex.org/name> "A" .', "nt")
1
>>> [str(s["name"]) for s in ds.query("SELECT ?name WHERE { ?s <http://ex.org/name> ?name }")]
['"A"']

See docs/USAGE.md#python in the Sparkles repository for the full guide."""

from __future__ import annotations

from sparkles._errors import (
    BackupError,
    BudgetExceededError,
    CancelledError,
    CatalogLockedError,
    ConflictError,
    DatasetLockedError,
    InvalidInputError,
    NotFoundError,
    ParseError,
    PermissionDeniedError,
    QueryTimeoutError,
    RdfSyntaxError,
    ServiceError,
    SparklesError,
    SparqlSyntaxError,
    StorageError,
    UnsupportedError,
    WriteRejectedError,
)

from sparkles._sparkles import (
    BlankNode,
    BranchSettings,
    Branches,
    CancelToken,
    Catalog,
    ChangeLogSetting,
    ChangePage,
    Commit,
    CommitChanges,
    CompactionSetting,
    Dataset,
    DatasetInfo,
    DefaultGraph,
    DescribeSetting,
    Diff,
    FEATURES,
    GeoIndex,
    GraphQL,
    GraphQLConfig,
    GuardSetting,
    History,
    HistoryChange,
    INFERRED_GRAPH,
    Indexes,
    Literal,
    NamedNode,
    PatchStats,
    Quad,
    QuadIterator,
    QuerySolution,
    QuerySolutions,
    QueryTriples,
    QuotaSetting,
    RdfFormat,
    RdfsSetting,
    ReasonReport,
    Reasoning,
    Reservation,
    RetentionSetting,
    Schema,
    Settings,
    ShaclReport,
    ShaclResult,
    ShexReport,
    ShexResult,
    Snapshot,
    Snapshots,
    StoredQueries,
    TextIndex,
    Transaction,
    Triple,
    UpdateStats,
    Validation,
    Variable,
    VectorIndexes,
    __version__,
    check_data,
    check_iri,
    check_langtag,
    convert_geometries,
    parse,
    parse_query,
    parse_update,
    preview_schedule,
    serialize,
)

__all__ = [
    "BackupError",
    "BlankNode",
    "BranchSettings",
    "Branches",
    "BudgetExceededError",
    "CancelToken",
    "CancelledError",
    "Catalog",
    "CatalogLockedError",
    "ChangeLogSetting",
    "ChangePage",
    "Commit",
    "CommitChanges",
    "CompactionSetting",
    "ConflictError",
    "Dataset",
    "DatasetInfo",
    "DatasetLockedError",
    "DefaultGraph",
    "DescribeSetting",
    "Diff",
    "FEATURES",
    "GeoIndex",
    "GraphQL",
    "GraphQLConfig",
    "GuardSetting",
    "History",
    "HistoryChange",
    "INFERRED_GRAPH",
    "Indexes",
    "InvalidInputError",
    "Literal",
    "NamedNode",
    "NotFoundError",
    "ParseError",
    "PatchStats",
    "PermissionDeniedError",
    "Quad",
    "QuadIterator",
    "QuerySolution",
    "QuerySolutions",
    "QueryTimeoutError",
    "QueryTriples",
    "QuotaSetting",
    "RdfFormat",
    "RdfSyntaxError",
    "RdfsSetting",
    "ReasonReport",
    "Reasoning",
    "Reservation",
    "RetentionSetting",
    "Schema",
    "ServiceError",
    "Settings",
    "ShaclReport",
    "ShaclResult",
    "ShexReport",
    "ShexResult",
    "Snapshot",
    "Snapshots",
    "SparklesError",
    "SparqlSyntaxError",
    "StorageError",
    "StoredQueries",
    "TextIndex",
    "Transaction",
    "Triple",
    "UnsupportedError",
    "UpdateStats",
    "Validation",
    "Variable",
    "VectorIndexes",
    "WriteRejectedError",
    "__version__",
    "check_data",
    "check_iri",
    "check_langtag",
    "convert_geometries",
    "parse",
    "parse_query",
    "parse_update",
    "preview_schedule",
    "serialize",
]

# The standard wheel enables file-system and S3 repositories.
if "backup" in FEATURES:
    from sparkles._sparkles import Backup, BackupRepository, Backups, Repositories
    __all__ += ["Backup", "BackupRepository", "Backups", "Repositories"]
