"""Type stubs of the compiled module `sparkles._sparkles` (re-exported by `sparkles`)."""

import builtins
import os
from collections.abc import Iterable, Iterator, Mapping
from types import TracebackType
from typing import IO, Any, Final, Union, final, overload

__version__: Final[str]
FEATURES: Final[frozenset[str]]
INFERRED_GRAPH: Final[str]

_Path = Union[str, os.PathLike[str]]
_Format = Union[RdfFormat, str]
_Subject = Union[NamedNode, BlankNode]
_Term = Union[NamedNode, BlankNode, Literal, Triple]
_GraphName = Union[NamedNode, BlankNode, DefaultGraph]
_Input = Union[str, bytes, IO[bytes], IO[str]]
_Output = Union[_Path, IO[bytes]]

# ------------------------------------------------------------------------- terms ----

@final
class NamedNode:
    """An IRI."""

    def __new__(cls, value: str) -> NamedNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class BlankNode:
    """A blank node; without a value it gets a fresh random label."""

    def __new__(cls, value: str | None = None) -> BlankNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class Literal:
    """A literal. A non-str value is converted by its Python type."""

    def __new__(
        cls,
        value: builtins.object,
        *,
        datatype: NamedNode | str | None = None,
        language: str | None = None,
        direction: str | None = None,
    ) -> Literal: ...
    @property
    def value(self) -> str: ...
    @property
    def datatype(self) -> NamedNode: ...
    @property
    def language(self) -> str | None: ...
    @property
    def direction(self) -> str | None: ...
    def to_python(self) -> Any: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Triple:
    """A triple, and an RDF 1.2 triple term."""

    def __new__(cls, subject: _Subject, predicate: NamedNode, object: _Term) -> Triple: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> NamedNode | BlankNode | Literal | Triple: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class Quad:
    """A triple in a graph; `graph_name` defaults to the default graph."""

    def __new__(
        cls,
        subject: _Subject,
        predicate: NamedNode,
        object: _Term,
        graph_name: _GraphName | str | None = None,
    ) -> Quad: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def graph_name(self) -> NamedNode | BlankNode | DefaultGraph: ...
    @property
    def triple(self) -> Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class DefaultGraph:
    """The default graph, as a graph name."""

    def __new__(cls) -> DefaultGraph: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Variable:
    """A query variable."""

    def __new__(cls, value: str) -> Variable: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

# ----------------------------------------------------------------------- formats ----

@final
class RdfFormat:
    """An RDF serialization format."""

    TURTLE: Final[RdfFormat]
    N_TRIPLES: Final[RdfFormat]
    N_QUADS: Final[RdfFormat]
    TRIG: Final[RdfFormat]
    N3: Final[RdfFormat]
    RDF_XML: Final[RdfFormat]
    JSON_LD: Final[RdfFormat]
    @property
    def name(self) -> str: ...
    @property
    def media_type(self) -> str: ...
    @property
    def file_extension(self) -> str: ...
    @property
    def iri(self) -> str: ...
    @property
    def supports_datasets(self) -> bool: ...
    @staticmethod
    def from_extension(extension: str) -> RdfFormat | None: ...
    @staticmethod
    def from_media_type(media_type: str) -> RdfFormat | None: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

def parse(
    input: _Input | None = None,
    format: _Format | None = None,
    *,
    path: _Path | None = None,
    base_iri: str | None = None,
    lenient: bool = False,
) -> QuadIterator:
    """Parse RDF without a dataset; triples are in the default graph."""

def serialize(
    input: Iterable[Triple | Quad],
    output: _Output | None = None,
    format: _Format | None = None,
    *,
    prefixes: Mapping[str, str] | None = None,
) -> bytes | None:
    """Serialize triples or quads; returns bytes when `output` is None."""

# ----------------------------------------------------------------------- results ----

@final
class QuadIterator:
    """An iterator of quads."""

    def __iter__(self) -> QuadIterator: ...
    def __next__(self) -> Quad: ...

@final
class QuerySolution:
    """One solution: a tuple of terms that also maps variable names to terms."""

    @overload
    def __getitem__(self, key: int, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @overload
    def __getitem__(self, key: str | Variable, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    def get(self, key: int | str | Variable, default: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple | None]: ...
    def __contains__(self, name: builtins.object, /) -> bool: ...
    def as_dict(self) -> dict[str, NamedNode | BlankNode | Literal | Triple]: ...
    def keys(self) -> list[str]: ...

@final
class QuerySolutions:
    """The solutions of a SELECT query."""

    @property
    def variables(self) -> list[Variable]: ...
    def __iter__(self) -> QuerySolutions: ...
    def __next__(self) -> QuerySolution: ...

@final
class QueryTriples:
    """The triples of a CONSTRUCT or DESCRIBE query."""

    def __iter__(self) -> QueryTriples: ...
    def __next__(self) -> Triple: ...

@final
class UpdateStats:
    """What a SPARQL Update request changed."""

    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def operations(self) -> int: ...

# ------------------------------------------------------ reasoning and validation ----

@final
class ReasonReport:
    """What a `Dataset.reason` run did."""

    @property
    def profile(self) -> str: ...
    @property
    def rules(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def inferred(self) -> int: ...
    @property
    def millis(self) -> int: ...
    @property
    def warnings(self) -> list[str]: ...

@final
class ShaclResult:
    """One SHACL validation result."""

    @property
    def focus_node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def path(self) -> str | None: ...
    @property
    def value(self) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @property
    def source_shape(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def constraint_component(self) -> NamedNode: ...
    @property
    def severity(self) -> NamedNode: ...
    @property
    def message(self) -> str | None: ...

@final
class ShaclReport:
    """A SHACL validation report; true when the data conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> list[ShaclResult]: ...
    def to_turtle(self) -> str: ...
    def __bool__(self) -> bool: ...

@final
class ShexResult:
    """The result of one (node, shape) pair."""

    @property
    def node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def shape(self) -> str: ...
    @property
    def conformant(self) -> bool: ...
    @property
    def reason(self) -> str | None: ...

@final
class ShexReport:
    """A ShEx result map; true when every node conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> list[ShexResult]: ...
    def to_json(self) -> str: ...
    def __bool__(self) -> bool: ...

# ----------------------------------------------------------------------- dataset ----

@final
class Transaction:
    """A write transaction; as a context manager it commits at the end of the block and
    rolls back if the block raises."""

    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> list[Quad]: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        _exc_value: BaseException | None = None,
        _traceback: TracebackType | None = None,
    ) -> bool: ...

_QueryResult = Union[QuerySolutions, bool, QueryTriples]

@final
class Dataset:
    """An RDF dataset in memory (`Dataset()`) or in a database directory
    (`Dataset(path)`)."""

    def __new__(cls, path: _Path | None = None, *, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def memory(*, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def open(path: _Path, *, union_default_graph: bool = False) -> Dataset: ...
    @property
    def path(self) -> str | None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Dataset: ...
    def __exit__(self, *_args: builtins.object) -> bool: ...
    def load(
        self,
        input: _Input | None = None,
        format: _Format | None = None,
        *,
        path: _Path | None = None,
        base_iri: str | None = None,
        to_graph: NamedNode | str | None = None,
        compression: str | None = None,
        lenient: bool = False,
    ) -> int: ...
    def load_files(self, paths: Iterable[_Path], *, to_graph: NamedNode | str | None = None) -> int: ...
    def query(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
    ) -> _QueryResult: ...
    def select(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
    ) -> QuerySolutions: ...
    def ask(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
    ) -> bool: ...
    def construct(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
    ) -> QueryTriples: ...
    def update(
        self,
        update: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
    ) -> UpdateStats: ...
    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> QuadIterator: ...
    def __iter__(self) -> QuadIterator: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def __len__(self) -> int: ...
    def named_graphs(self) -> list[NamedNode | BlankNode]: ...
    def clear_graph(self, graph_name: _GraphName | str) -> int: ...
    def clear(self) -> None: ...
    def transaction(self) -> Transaction: ...
    def dump(
        self,
        output: _Output | None = None,
        format: _Format | None = None,
        *,
        from_graph: _GraphName | str | None = None,
        compression: str | None = None,
    ) -> bytes | None: ...
    def compact(self) -> None: ...
    def backup(self, directory: _Path) -> str: ...
    @property
    def prefixes(self) -> dict[str, str]: ...
    def set_prefix(self, prefix: str, iri: str) -> None: ...
    def reason(self, profile: str = "rdfs", *, rules: str | None = None) -> ReasonReport: ...
    def clear_inferences(self) -> int: ...
    def validate_shacl(
        self,
        shapes: str | bytes | None = None,
        *,
        format: _Format | None = None,
        shapes_graph: NamedNode | str | None = None,
        data_graph: NamedNode | str | None = None,
        include_inferred: bool = False,
    ) -> ShaclReport: ...
    def validate_shex(
        self,
        schema: str,
        shape_map: str,
        *,
        format: str | None = None,
        data_graph: NamedNode | str | None = None,
        include_inferred: bool = False,
    ) -> ShexReport: ...
