"""Type stubs of the compiled module `sparkles._sparkles` (re-exported by `sparkles`)."""

import builtins
import os
from collections.abc import Iterable, Iterator, Mapping
from types import TracebackType
from typing import IO, Any, Final, Union, final, overload

__version__: Final[str]
FEATURES: Final[frozenset[str]]
INFERRED_GRAPH: Final[str]

_Path = Union[str, os.PathLike[str]]
_Format = Union[RdfFormat, str]
_Subject = Union[NamedNode, BlankNode]
_Term = Union[NamedNode, BlankNode, Literal, Triple]
_GraphName = Union[NamedNode, BlankNode, DefaultGraph]
_Input = Union[str, bytes, IO[bytes], IO[str]]
_Output = Union[_Path, IO[bytes]]

# ------------------------------------------------------------------------- terms ----

@final
class NamedNode:
    """An IRI."""

    def __new__(cls, value: str) -> NamedNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class BlankNode:
    """A blank node; without a value it gets a fresh random label."""

    def __new__(cls, value: str | None = None) -> BlankNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class Literal:
    """A literal. A non-str value is converted by its Python type."""

    def __new__(
        cls,
        value: builtins.object,
        *,
        datatype: NamedNode | str | None = None,
        language: str | None = None,
        direction: str | None = None,
    ) -> Literal: ...
    @property
    def value(self) -> str: ...
    @property
    def datatype(self) -> NamedNode: ...
    @property
    def language(self) -> str | None: ...
    @property
    def direction(self) -> str | None: ...
    def to_python(self) -> Any: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Triple:
    """A triple, and an RDF 1.2 triple term."""

    def __new__(cls, subject: _Subject, predicate: NamedNode, object: _Term) -> Triple: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> NamedNode | BlankNode | Literal | Triple: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class Quad:
    """A triple in a graph; `graph_name` defaults to the default graph."""

    def __new__(
        cls,
        subject: _Subject,
        predicate: NamedNode,
        object: _Term,
        graph_name: _GraphName | str | None = None,
    ) -> Quad: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def graph_name(self) -> NamedNode | BlankNode | DefaultGraph: ...
    @property
    def triple(self) -> Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class DefaultGraph:
    """The default graph, as a graph name."""

    def __new__(cls) -> DefaultGraph: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Variable:
    """A query variable."""

    def __new__(cls, value: str) -> Variable: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

# ----------------------------------------------------------------------- formats ----

@final
class RdfFormat:
    """An RDF serialization format."""

    TURTLE: Final[RdfFormat]
    N_TRIPLES: Final[RdfFormat]
    N_QUADS: Final[RdfFormat]
    TRIG: Final[RdfFormat]
    N3: Final[RdfFormat]
    RDF_XML: Final[RdfFormat]
    JSON_LD: Final[RdfFormat]
    @property
    def name(self) -> str: ...
    @property
    def media_type(self) -> str: ...
    @property
    def file_extension(self) -> str: ...
    @property
    def iri(self) -> str: ...
    @property
    def supports_datasets(self) -> bool: ...
    @staticmethod
    def from_extension(extension: str) -> RdfFormat | None: ...
    @staticmethod
    def from_media_type(media_type: str) -> RdfFormat | None: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

def parse(
    input: _Input | None = None,
    format: _Format | None = None,
    *,
    path: _Path | None = None,
    base_iri: str | None = None,
    compression: str | None = None,
    lenient: bool = False,
) -> QuadIterator:
    """Parse RDF without a dataset as it is read; triples are in the default graph."""

def serialize(
    input: Iterable[Triple | Quad],
    output: _Output | None = None,
    format: _Format | None = None,
    *,
    prefixes: Mapping[str, str] | None = None,
) -> bytes | None:
    """Serialize triples or quads; returns bytes when `output` is None."""

# ----------------------------------------------------------------------- results ----

@final
class QuadIterator:
    """An iterator of quads."""

    def __iter__(self) -> QuadIterator: ...
    def __next__(self) -> Quad: ...

@final
class QuerySolution:
    """One solution: a tuple of terms that also maps variable names to terms."""

    @overload
    def __getitem__(self, key: int, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @overload
    def __getitem__(self, key: str | Variable, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    def get(self, key: int | str | Variable, default: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple | None]: ...
    def __contains__(self, name: builtins.object, /) -> bool: ...
    def as_dict(self) -> dict[str, NamedNode | BlankNode | Literal | Triple]: ...
    def keys(self) -> list[str]: ...

@final
class QuerySolutions:
    """The solutions of a SELECT query."""

    @property
    def variables(self) -> list[Variable]: ...
    def __iter__(self) -> QuerySolutions: ...
    def __next__(self) -> QuerySolution: ...
    def serialize(self, output: _Output | None = None, format: str = "json") -> bytes | None:
        """Write the solutions as SPARQL results (json, xml, csv or tsv); consumes them."""

@final
class QueryTriples:
    """The triples of a CONSTRUCT or DESCRIBE query."""

    def __iter__(self) -> QueryTriples: ...
    def __next__(self) -> Triple: ...
    def serialize(
        self,
        output: _Output | None = None,
        format: _Format | None = None,
        *,
        prefixes: Mapping[str, str] | None = None,
    ) -> bytes | None:
        """Write the remaining triples in an RDF format (Turtle by default)."""

@final
class UpdateStats:
    """What a SPARQL Update request changed."""

    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def operations(self) -> int: ...

# ------------------------------------------------------ reasoning and validation ----

@final
class ReasonReport:
    """What a `Dataset.reason` run did."""

    @property
    def profile(self) -> str: ...
    @property
    def rules(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def inferred(self) -> int: ...
    @property
    def millis(self) -> int: ...
    @property
    def warnings(self) -> list[str]: ...

@final
class ShaclResult:
    """One SHACL validation result."""

    @property
    def focus_node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def path(self) -> str | None: ...
    @property
    def value(self) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @property
    def source_shape(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def constraint_component(self) -> NamedNode: ...
    @property
    def severity(self) -> NamedNode: ...
    @property
    def message(self) -> str | None: ...

@final
class ShaclReport:
    """A SHACL validation report; true when the data conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> list[ShaclResult]: ...
    def to_turtle(self) -> str: ...
    def __bool__(self) -> bool: ...

@final
class ShexResult:
    """The result of one (node, shape) pair."""

    @property
    def node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def shape(self) -> str: ...
    @property
    def conformant(self) -> bool: ...
    @property
    def reason(self) -> str | None: ...

@final
class ShexReport:
    """A ShEx result map; true when every node conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> list[ShexResult]: ...
    def to_json(self) -> str: ...
    def __bool__(self) -> bool: ...

# ----------------------------------------------------------------------- dataset ----

@final
class CancelToken:
    """Cancels the queries and updates it is passed to; `cancel()` works from any
    thread."""

    def __new__(cls) -> CancelToken: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

@final
class Transaction:
    """A write transaction; as a context manager it commits at the end of the block and
    rolls back if the block raises."""

    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> list[Quad]: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def query(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
    ) -> _QueryResult: ...
    def update(
        self,
        update: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
    ) -> UpdateStats: ...
    def _apply(self, ops: Iterable[tuple[bool, Quad]]) -> tuple[int, int, dict[str, str]]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        _exc_value: BaseException | None = None,
        _traceback: TracebackType | None = None,
    ) -> bool: ...

_QueryResult = Union[QuerySolutions, bool, QueryTriples]

@final
class Dataset:
    """An RDF dataset in memory (`Dataset()`) or in a database directory
    (`Dataset(path)`)."""

    def __new__(cls, path: _Path | None = None, *, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def memory(*, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def open(path: _Path, *, union_default_graph: bool = False) -> Dataset: ...
    @property
    def path(self) -> str | None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Dataset: ...
    def __exit__(self, *_args: builtins.object) -> bool: ...
    def load(
        self,
        input: _Input | None = None,
        format: _Format | None = None,
        *,
        path: _Path | None = None,
        base_iri: str | None = None,
        to_graph: NamedNode | str | None = None,
        compression: str | None = None,
        lenient: bool = False,
    ) -> int: ...
    def load_files(self, paths: Iterable[_Path], *, to_graph: NamedNode | str | None = None) -> int: ...
    def query(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
    ) -> _QueryResult: ...
    def select(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
    ) -> QuerySolutions: ...
    def ask(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
    ) -> bool: ...
    def construct(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
    ) -> QueryTriples: ...
    def update(
        self,
        update: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
    ) -> UpdateStats: ...
    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> QuadIterator: ...
    def _apply(self, ops: Iterable[tuple[bool, Quad]]) -> tuple[int, int, dict[str, str]]: ...
    def _quads_by_triple(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
    ) -> QuadIterator: ...
    def __iter__(self) -> QuadIterator: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def __len__(self) -> int: ...
    def named_graphs(self) -> list[NamedNode | BlankNode]: ...
    def clear_graph(self, graph_name: _GraphName | str) -> int: ...
    def clear(self) -> None: ...
    def transaction(self) -> Transaction: ...
    def dump(
        self,
        output: _Output | None = None,
        format: _Format | None = None,
        *,
        from_graph: _GraphName | str | None = None,
        compression: str | None = None,
    ) -> bytes | None: ...
    def compact(self) -> None: ...
    def backup(self, directory: _Path) -> str: ...
    @property
    def prefixes(self) -> dict[str, str]: ...
    def set_prefix(self, prefix: str, iri: str) -> None: ...
    def reason(self, profile: str = "rdfs", *, rules: str | None = None) -> ReasonReport: ...
    def clear_inferences(self) -> int: ...
    def validate_shacl(
        self,
        shapes: str | bytes | None = None,
        *,
        format: _Format | None = None,
        shapes_graph: NamedNode | str | None = None,
        data_graph: NamedNode | str | None = None,
        include_inferred: bool = False,
    ) -> ShaclReport: ...
    def validate_shex(
        self,
        schema: str,
        shape_map: str,
        *,
        format: str | None = None,
        data_graph: NamedNode | str | None = None,
        include_inferred: bool = False,
    ) -> ShexReport: ...
    @property
    def head_commit(self) -> Commit: ...
    def commits(self, limit: int = 100, *, before: int | None = None, after: int | None = None) -> list[Commit]: ...
    def create_snapshot(
        self,
        name: str,
        at: int | str | None = None,
        *,
        note: str | None = None,
        expires_ms: int | None = None,
    ) -> Snapshot: ...
    def snapshots(self) -> list[Snapshot]: ...
    def delete_snapshot(self, name: str) -> bool: ...
    def history(self) -> dict[str, Any]: ...
    def set_retention(
        self,
        *,
        keep_commits: int | None = None,
        keep_age: float | None = None,
        max_bytes: int | None = None,
    ) -> dict[str, Any]: ...
    def clone_to(
        self,
        directory: _Path,
        *,
        at: int | str | None = None,
        exclude_graphs: Iterable[NamedNode | str] | None = None,
    ) -> dict[str, Any]: ...
    def enable_text(self, config: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
    def rebuild_text(self) -> dict[str, Any]: ...
    def disable_text(self) -> None: ...
    def text_status(self) -> dict[str, Any] | None: ...
    def create_vector_index(
        self,
        name: str,
        predicate: NamedNode | str,
        dimension: int,
        *,
        options: Mapping[str, Any] | None = None,
    ) -> bool: ...
    def drop_vector_index(self, name: str) -> None: ...
    def rebuild_vector_index(self, name: str) -> None: ...
    def reembed_vector_index(self, name: str) -> None: ...
    def embed(
        self,
        *,
        timeout: float = 3600.0,
        allow_private: bool = True,
        secrets: Mapping[str, str] | None = None,
    ) -> None: ...
    def vector_index(self, name: str, *, wait: bool = False) -> dict[str, Any] | None: ...
    def vector_indexes(self) -> list[dict[str, Any]]: ...
    def set_write_validation(self, config: Mapping[str, Any] | None) -> dict[str, Any]: ...
    def write_validation(self) -> dict[str, Any] | None: ...

@final
class Commit:
    """One commit: the state after a write that changed data."""

    @property
    def seq(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def quads(self) -> int: ...

@final
class Snapshot:
    """A named snapshot: a commit kept readable under a name."""

    @property
    def name(self) -> str: ...
    @property
    def seq(self) -> int: ...
    @property
    def created_ms(self) -> int: ...
    @property
    def note(self) -> str | None: ...
    @property
    def expires_ms(self) -> int | None: ...

# ------------------------------------------------------------------ query builder ----

_Node = Union[str, int, float, NamedNode, BlankNode, Literal, Triple, Variable]
_Expr = _Node
_Target = Union[str, NamedNode, DefaultGraph]

@final
class SelectBuilder:
    """Builds a SELECT query."""

    def __new__(cls) -> SelectBuilder: ...
    def prefix(self, prefix: str, iri: str) -> SelectBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> SelectBuilder: ...
    def base(self, iri: str) -> SelectBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> SelectBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> SelectBuilder: ...
    def add_where(self, w: WhereBuilder) -> SelectBuilder: ...
    def group(self, w: WhereBuilder) -> SelectBuilder: ...
    def optional(self, w: WhereBuilder) -> SelectBuilder: ...
    def union(self, *branches: WhereBuilder) -> SelectBuilder: ...
    def minus(self, w: WhereBuilder) -> SelectBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> SelectBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> SelectBuilder: ...
    def filter(self, e: _Expr) -> SelectBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> SelectBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> SelectBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> SelectBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> SelectBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> SelectBuilder: ...
    def sub_select(self, q: SelectBuilder) -> SelectBuilder: ...
    def order_by(self, e: _Expr) -> SelectBuilder: ...
    def order_by_desc(self, e: _Expr) -> SelectBuilder: ...
    def limit(self, n: int) -> SelectBuilder: ...
    def offset(self, n: int) -> SelectBuilder: ...
    def from_(self, g: _Node) -> SelectBuilder: ...
    def from_named(self, g: _Node) -> SelectBuilder: ...
    def select(self, *vars: _Node) -> SelectBuilder: ...
    def select_expr(self, e: _Expr, alias: _Node) -> SelectBuilder: ...
    def select_all(self) -> SelectBuilder: ...
    def distinct(self) -> SelectBuilder: ...
    def reduced(self) -> SelectBuilder: ...
    def group_by(self, e: _Expr, alias: _Node | None = None) -> SelectBuilder: ...
    def having(self, e: _Expr) -> SelectBuilder: ...

@final
class AskBuilder:
    """Builds an ASK query."""

    def __new__(cls) -> AskBuilder: ...
    def prefix(self, prefix: str, iri: str) -> AskBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> AskBuilder: ...
    def base(self, iri: str) -> AskBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> AskBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> AskBuilder: ...
    def add_where(self, w: WhereBuilder) -> AskBuilder: ...
    def group(self, w: WhereBuilder) -> AskBuilder: ...
    def optional(self, w: WhereBuilder) -> AskBuilder: ...
    def union(self, *branches: WhereBuilder) -> AskBuilder: ...
    def minus(self, w: WhereBuilder) -> AskBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> AskBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> AskBuilder: ...
    def filter(self, e: _Expr) -> AskBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> AskBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> AskBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> AskBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> AskBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> AskBuilder: ...
    def sub_select(self, q: SelectBuilder) -> AskBuilder: ...
    def from_(self, g: _Node) -> AskBuilder: ...
    def from_named(self, g: _Node) -> AskBuilder: ...

@final
class ConstructBuilder:
    """Builds a CONSTRUCT query."""

    def __new__(cls) -> ConstructBuilder: ...
    def prefix(self, prefix: str, iri: str) -> ConstructBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> ConstructBuilder: ...
    def base(self, iri: str) -> ConstructBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> ConstructBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> ConstructBuilder: ...
    def add_where(self, w: WhereBuilder) -> ConstructBuilder: ...
    def group(self, w: WhereBuilder) -> ConstructBuilder: ...
    def optional(self, w: WhereBuilder) -> ConstructBuilder: ...
    def union(self, *branches: WhereBuilder) -> ConstructBuilder: ...
    def minus(self, w: WhereBuilder) -> ConstructBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> ConstructBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> ConstructBuilder: ...
    def filter(self, e: _Expr) -> ConstructBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> ConstructBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> ConstructBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> ConstructBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> ConstructBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> ConstructBuilder: ...
    def sub_select(self, q: SelectBuilder) -> ConstructBuilder: ...
    def order_by(self, e: _Expr) -> ConstructBuilder: ...
    def order_by_desc(self, e: _Expr) -> ConstructBuilder: ...
    def limit(self, n: int) -> ConstructBuilder: ...
    def offset(self, n: int) -> ConstructBuilder: ...
    def from_(self, g: _Node) -> ConstructBuilder: ...
    def from_named(self, g: _Node) -> ConstructBuilder: ...
    def construct(self, s: _Node, p: _Node, o: _Node) -> ConstructBuilder: ...

@final
class DescribeBuilder:
    """Builds a DESCRIBE query."""

    def __new__(cls) -> DescribeBuilder: ...
    def prefix(self, prefix: str, iri: str) -> DescribeBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> DescribeBuilder: ...
    def base(self, iri: str) -> DescribeBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> DescribeBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> DescribeBuilder: ...
    def add_where(self, w: WhereBuilder) -> DescribeBuilder: ...
    def group(self, w: WhereBuilder) -> DescribeBuilder: ...
    def optional(self, w: WhereBuilder) -> DescribeBuilder: ...
    def union(self, *branches: WhereBuilder) -> DescribeBuilder: ...
    def minus(self, w: WhereBuilder) -> DescribeBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> DescribeBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> DescribeBuilder: ...
    def filter(self, e: _Expr) -> DescribeBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> DescribeBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> DescribeBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> DescribeBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> DescribeBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> DescribeBuilder: ...
    def sub_select(self, q: SelectBuilder) -> DescribeBuilder: ...
    def order_by(self, e: _Expr) -> DescribeBuilder: ...
    def order_by_desc(self, e: _Expr) -> DescribeBuilder: ...
    def limit(self, n: int) -> DescribeBuilder: ...
    def offset(self, n: int) -> DescribeBuilder: ...
    def from_(self, g: _Node) -> DescribeBuilder: ...
    def from_named(self, g: _Node) -> DescribeBuilder: ...
    def describe(self, *resources: _Node) -> DescribeBuilder: ...

@final
class UpdateBuilder:
    """Builds a SPARQL Update request."""

    def __new__(cls) -> UpdateBuilder: ...
    def prefix(self, prefix: str, iri: str) -> UpdateBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> UpdateBuilder: ...
    def base(self, iri: str) -> UpdateBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> UpdateBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> UpdateBuilder: ...
    def add_where(self, w: WhereBuilder) -> UpdateBuilder: ...
    def group(self, w: WhereBuilder) -> UpdateBuilder: ...
    def optional(self, w: WhereBuilder) -> UpdateBuilder: ...
    def union(self, *branches: WhereBuilder) -> UpdateBuilder: ...
    def minus(self, w: WhereBuilder) -> UpdateBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> UpdateBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> UpdateBuilder: ...
    def filter(self, e: _Expr) -> UpdateBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> UpdateBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> UpdateBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> UpdateBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> UpdateBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> UpdateBuilder: ...
    def sub_select(self, q: SelectBuilder) -> UpdateBuilder: ...
    def then(self) -> UpdateBuilder: ...
    def insert_data(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete_data(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete_where(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def insert(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def with_(self, g: _Node) -> UpdateBuilder: ...
    def using(self, g: _Node) -> UpdateBuilder: ...
    def using_named(self, g: _Node) -> UpdateBuilder: ...
    def load(self, source: _Node, *, into: _Node | None = None) -> UpdateBuilder: ...
    def clear(self, target_: _Target) -> UpdateBuilder: ...
    def drop(self, target_: _Target) -> UpdateBuilder: ...
    def create(self, g: _Node) -> UpdateBuilder: ...
    def add(self, source: _Target, to: _Target) -> UpdateBuilder: ...
    def copy(self, source: _Target, to: _Target) -> UpdateBuilder: ...
    def move_(self, source: _Target, to: _Target) -> UpdateBuilder: ...

@final
class WhereBuilder:
    """A group of patterns for the nested patterns of a builder."""

    def __new__(cls) -> WhereBuilder: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> WhereBuilder: ...
    def add_where(self, w: WhereBuilder) -> WhereBuilder: ...
    def group(self, w: WhereBuilder) -> WhereBuilder: ...
    def optional(self, w: WhereBuilder) -> WhereBuilder: ...
    def union(self, *branches: WhereBuilder) -> WhereBuilder: ...
    def minus(self, w: WhereBuilder) -> WhereBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> WhereBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> WhereBuilder: ...
    def filter(self, e: _Expr) -> WhereBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> WhereBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> WhereBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> WhereBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> WhereBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> WhereBuilder: ...
    def sub_select(self, q: SelectBuilder) -> WhereBuilder: ...
