"""Type stubs of the compiled module `sparkles._sparkles` (re-exported by `sparkles`)."""

import builtins
import os
from collections.abc import Callable, Iterable, Iterator, Mapping
from types import TracebackType
from typing import IO, Any, Final, Union, final, overload

__version__: Final[str]
FEATURES: Final[frozenset[str]]
INFERRED_GRAPH: Final[str]

_Path = Union[str, os.PathLike[str]]
_Format = Union[RdfFormat, str]
# a DESCRIBE mode ("cbd", "scbd", "outgoing"), or options: mode, labels, reifiers,
# max_triples and max_depth (None or 0: no limit)
_Describe = Union[str, Mapping[str, Union[str, bool, int, None]]]
_Subject = Union[NamedNode, BlankNode]
_Term = Union[NamedNode, BlankNode, Literal, Triple]
_GraphName = Union[NamedNode, BlankNode, DefaultGraph]
_Input = Union[str, bytes, IO[bytes], IO[str]]
_Output = Union[_Path, IO[bytes]]

# ------------------------------------------------------------------------- terms ----

@final
class NamedNode:
    """An IRI."""

    def __new__(cls, value: str) -> NamedNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class BlankNode:
    """A blank node; without a value it gets a fresh random label."""

    def __new__(cls, value: str | None = None) -> BlankNode: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

@final
class Literal:
    """A literal. A non-str value is converted by its Python type."""

    def __new__(
        cls,
        value: builtins.object,
        *,
        datatype: NamedNode | str | None = None,
        language: str | None = None,
        direction: str | None = None,
    ) -> Literal: ...
    @property
    def value(self) -> str: ...
    @property
    def datatype(self) -> NamedNode: ...
    @property
    def language(self) -> str | None: ...
    @property
    def direction(self) -> str | None: ...
    def to_python(self) -> Any: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Triple:
    """A triple, and an RDF 1.2 triple term."""

    def __new__(cls, subject: _Subject, predicate: NamedNode, object: _Term) -> Triple: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> NamedNode | BlankNode | Literal | Triple: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class Quad:
    """A triple in a graph; `graph_name` defaults to the default graph."""

    def __new__(
        cls,
        subject: _Subject,
        predicate: NamedNode,
        object: _Term,
        graph_name: _GraphName | str | None = None,
    ) -> Quad: ...
    @property
    def subject(self) -> NamedNode | BlankNode: ...
    @property
    def predicate(self) -> NamedNode: ...
    @property
    def object(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def graph_name(self) -> NamedNode | BlankNode | DefaultGraph: ...
    @property
    def triple(self) -> Triple: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[Any, ...]: ...

@final
class DefaultGraph:
    """The default graph, as a graph name."""

    def __new__(cls) -> DefaultGraph: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Variable:
    """A query variable."""

    def __new__(cls, value: str) -> Variable: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str]: ...

# ----------------------------------------------------------------------- formats ----

@final
class RdfFormat:
    """An RDF serialization format."""

    TURTLE: Final[RdfFormat]
    N_TRIPLES: Final[RdfFormat]
    N_QUADS: Final[RdfFormat]
    TRIG: Final[RdfFormat]
    N3: Final[RdfFormat]
    RDF_XML: Final[RdfFormat]
    JSON_LD: Final[RdfFormat]
    TRIX: Final[RdfFormat]
    RDF_THRIFT: Final[RdfFormat]
    RDF_PROTOBUF: Final[RdfFormat]
    RDF_JSON: Final[RdfFormat]
    @property
    def name(self) -> str: ...
    @property
    def media_type(self) -> str: ...
    @property
    def file_extension(self) -> str: ...
    @property
    def iri(self) -> str: ...
    @property
    def supports_datasets(self) -> bool: ...
    @staticmethod
    def from_extension(extension: str) -> RdfFormat | None: ...
    @staticmethod
    def from_media_type(media_type: str) -> RdfFormat | None: ...
    def __eq__(self, other: builtins.object, /) -> bool: ...
    def __ne__(self, other: builtins.object, /) -> bool: ...
    def __hash__(self) -> int: ...

def parse(
    input: _Input | None = None,
    format: _Format | None = None,
    *,
    path: _Path | None = None,
    base_iri: str | None = None,
    compression: str | None = None,
    lenient: bool = False,
) -> QuadIterator:
    """Parse RDF without a dataset as it is read; triples are in the default graph."""

def serialize(
    input: Iterable[Triple | Quad],
    output: _Output | None = None,
    format: _Format | None = None,
    *,
    prefixes: Mapping[str, str] | None = None,
) -> bytes | None:
    """Serialize triples or quads; returns bytes when `output` is None."""

# ----------------------------------------------------------------------- results ----

@final
class QuadIterator:
    """An iterator of quads."""

    def __iter__(self) -> QuadIterator: ...
    def __next__(self) -> Quad: ...

@final
class QuerySolution:
    """One solution: a tuple of terms that also maps variable names to terms."""

    @overload
    def __getitem__(self, key: int, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @overload
    def __getitem__(self, key: str | Variable, /) -> NamedNode | BlankNode | Literal | Triple | None: ...
    def get(self, key: int | str | Variable, default: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NamedNode | BlankNode | Literal | Triple | None]: ...
    def __contains__(self, name: builtins.object, /) -> bool: ...
    def as_dict(self) -> dict[str, NamedNode | BlankNode | Literal | Triple]: ...
    def keys(self) -> builtins.list[str]: ...

@final
class QuerySolutions:
    """The solutions of a SELECT query."""

    @property
    def variables(self) -> builtins.list[Variable]: ...
    def __iter__(self) -> QuerySolutions: ...
    def __next__(self) -> QuerySolution: ...
    def serialize(self, output: _Output | None = None, format: str = "json") -> bytes | None:
        """Write the solutions as SPARQL results (json, xml, csv or tsv); consumes them."""

@final
class QueryTriples:
    """The triples of a CONSTRUCT or DESCRIBE query."""

    def __iter__(self) -> QueryTriples: ...
    def __next__(self) -> Triple: ...
    @property
    def quads(self) -> builtins.list[Quad]:
        """The quads in named graphs of a CONSTRUCT with Jena ARQ's `GRAPH` template
        blocks. The iteration yields the default graph's triples."""
    def serialize(
        self,
        output: _Output | None = None,
        format: _Format | None = None,
        *,
        prefixes: Mapping[str, str] | None = None,
    ) -> bytes | None:
        """Write the remaining triples in an RDF format (Turtle by default), and the
        quads too in a dataset format."""

@final
class UpdateStats:
    """What a SPARQL Update request changed."""

    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def operations(self) -> int: ...

@final
class PatchStats:
    """What applying an RDF Patch did."""

    @property
    def committed(self) -> bool: ...
    @property
    def commit(self) -> int: ...
    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def aborted(self) -> bool: ...
    @property
    def prev_checked(self) -> bool: ...
    @property
    def prefixes_set(self) -> int: ...
    @property
    def prefixes_removed(self) -> int: ...

# ------------------------------------------------------ reasoning and validation ----

@final
class ReasonReport:
    """What a `Dataset.reasoning.run` run did."""

    @property
    def profile(self) -> str: ...
    @property
    def rules(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def inferred(self) -> int: ...
    @property
    def millis(self) -> int: ...
    @property
    def warnings(self) -> builtins.list[str]: ...

@final
class ShaclResult:
    """One SHACL validation result."""

    @property
    def focus_node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def path(self) -> str | None: ...
    @property
    def value(self) -> NamedNode | BlankNode | Literal | Triple | None: ...
    @property
    def source_shape(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def constraint_component(self) -> NamedNode: ...
    @property
    def severity(self) -> NamedNode: ...
    @property
    def message(self) -> str | None: ...

@final
class ShaclReport:
    """A SHACL validation report; true when the data conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> builtins.list[ShaclResult]: ...
    def to_turtle(self) -> str: ...
    def __bool__(self) -> bool: ...

@final
class ShexResult:
    """The result of one (node, shape) pair."""

    @property
    def node(self) -> NamedNode | BlankNode | Literal | Triple: ...
    @property
    def shape(self) -> str: ...
    @property
    def conformant(self) -> bool: ...
    @property
    def reason(self) -> str | None: ...

@final
class ShexReport:
    """A ShEx result map; true when every node conforms."""

    @property
    def conforms(self) -> bool: ...
    @property
    def results(self) -> builtins.list[ShexResult]: ...
    def to_json(self) -> str: ...
    def __bool__(self) -> bool: ...

# ----------------------------------------------------------------------- dataset ----

@final
class CancelToken:
    """Cancels the queries and updates it is passed to; `cancel()` works from any
    thread."""

    def __new__(cls) -> CancelToken: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

@final
class Transaction:
    """A write transaction; as a context manager it commits at the end of the block and
    rolls back if the block raises."""

    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> builtins.list[Quad]: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def query(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        describe: _Describe | None = None,
    ) -> _QueryResult: ...
    def update(
        self,
        update: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
    ) -> UpdateStats: ...
    def _apply(self, ops: Iterable[tuple[bool, Quad]]) -> tuple[int, int, dict[str, str]]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        _exc_value: BaseException | None = None,
        _traceback: TracebackType | None = None,
    ) -> bool: ...

_QueryResult = Union[QuerySolutions, bool, QueryTriples]

@final
class Dataset:
    """An RDF dataset in memory (`Dataset()`) or in a database directory
    (`Dataset(path)`)."""

    def __new__(cls, path: _Path | None = None, *, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def memory(*, union_default_graph: bool = False) -> Dataset: ...
    @staticmethod
    def open(path: _Path, *, union_default_graph: bool = False) -> Dataset: ...
    @property
    def path(self) -> str | None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Dataset: ...
    def __exit__(self, *_args: builtins.object) -> bool: ...
    def load(
        self,
        input: _Input | None = None,
        format: _Format | None = None,
        *,
        path: _Path | None = None,
        base_iri: str | None = None,
        to_graph: NamedNode | str | None = None,
        compression: str | None = None,
        lenient: bool = False,
        mapping: _Path | None = None,
        template: _Path | None = None,
        key: str | None = None,
        parse_mode: str = "auto",
        auto_buffer_bytes: int | None = None,
    ) -> int: ...
    def load_files(self, paths: Iterable[_Path], *, to_graph: NamedNode | str | None = None, parse_mode: str = "auto", auto_buffer_bytes: int | None = None) -> int: ...
    def query(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
        describe: _Describe | None = None,
    ) -> _QueryResult: ...
    def select(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
        describe: _Describe | None = None,
    ) -> QuerySolutions: ...
    def ask(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
        describe: _Describe | None = None,
    ) -> bool: ...
    def construct(
        self,
        query: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        bindings: Mapping[str | Variable, _Term] | None = None,
        default_graph: Iterable[NamedNode | str] | None = None,
        named_graphs: Iterable[NamedNode | str] | None = None,
        include_inferred: bool = False,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
        at: int | str | None = None,
        describe: _Describe | None = None,
    ) -> QueryTriples: ...
    def update(
        self,
        update: str,
        *,
        base_iri: str | None = None,
        prefixes: Mapping[str, str] | None = None,
        timeout: float | None = None,
        max_rows: int | None = None,
        max_memory_bytes: int | None = None,
        max_rows_produced: int | None = None,
        cancel: CancelToken | None = None,
    ) -> UpdateStats: ...
    def apply_patch(
        self, data: str | bytes, binary: bool = False, *, message: str | None = None
    ) -> PatchStats: ...
    def add(self, quad: Quad | Triple) -> bool: ...
    def remove(self, quad: Quad | Triple) -> bool: ...
    def extend(self, quads: Iterable[Quad | Triple]) -> int: ...
    def quads_for_pattern(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
        graph_name: _GraphName | str | None = None,
    ) -> QuadIterator: ...
    def _apply(self, ops: Iterable[tuple[bool, Quad]]) -> tuple[int, int, dict[str, str]]: ...
    def _quads_by_triple(
        self,
        subject: _Subject | None = None,
        predicate: NamedNode | None = None,
        object: _Term | None = None,
    ) -> QuadIterator: ...
    def __iter__(self) -> QuadIterator: ...
    def __contains__(self, quad: Quad | Triple, /) -> bool: ...
    def __len__(self) -> int: ...
    def named_graphs(self) -> builtins.list[NamedNode | BlankNode]: ...
    def clear_graph(self, graph_name: _GraphName | str) -> int: ...
    def clear(self) -> None: ...
    def transaction(self) -> Transaction: ...
    def dump(
        self,
        output: _Output | None = None,
        format: _Format | None = None,
        *,
        from_graph: _GraphName | str | None = None,
        compression: str | None = None,
    ) -> bytes | None: ...
    def backup(self, directory: _Path) -> str: ...
    @property
    def prefixes(self) -> dict[str, str]: ...
    def set_prefix(self, prefix: str, iri: str) -> None: ...
    @property
    def head_commit(self) -> Commit: ...
    def compact(self, /, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def clone_to(self, /, directory: _Path, *, at: int | str | None = None, graphs: Iterable[_GraphName | str] | None = None, inferences: str = "copy", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def clone_to_memory(self, /, *, at: int | str | None = None, graphs: Iterable[_GraphName | str] | None = None, inferences: str = "copy", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> Dataset: ...
    def remove_prefix(self, /, prefix: str) -> bool: ...
    def clear_cache(self, /) -> None: ...
    def stats(self, /, *, at: int | str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def explain(self, /, query: str, *, base_iri: str | None = None, prefixes: Mapping[str, str] | None = None) -> dict[str, Any]: ...
    def replace(self, /, input: _Input | None = None, *, format: _Format | None = None, path: _Path | None = None, target: _GraphName | str | None = None, base_iri: str | None = None, compression: str | None = None, lenient: bool = False, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def backups(self, /, repository: BackupRepository) -> Backups: ...
    def branch(self, /, name: str) -> Dataset: ...
    @property
    def indexes(self) -> Indexes: ...
    @property
    def branches(self) -> Branches: ...
    @property
    def queries(self) -> StoredQueries: ...
    @property
    def settings(self) -> Settings: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def reasoning(self) -> Reasoning: ...
    @property
    def graphql(self) -> GraphQL: ...
    @property
    def dataset_id(self) -> str: ...
    @property
    def snapshots(self) -> Snapshots: ...
    @property
    def validation(self) -> Validation: ...
    @property
    def history(self) -> History: ...

@final
class Commit:
    """One commit: the state after a write that changed data."""

    @property
    def seq(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def inserted(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def quads(self) -> int: ...
    @property
    def message(self) -> str | None: ...
    @property
    def digest(self) -> str | None: ...

@final
class Snapshot:
    """A named snapshot: a commit kept readable under a name."""

    @property
    def name(self) -> str: ...
    @property
    def seq(self) -> int: ...
    @property
    def created_ms(self) -> int: ...
    @property
    def note(self) -> str | None: ...
    @property
    def expires_ms(self) -> int | None: ...

# ------------------------------------------------------------------ query builder ----

_Node = Union[str, int, float, NamedNode, BlankNode, Literal, Triple, Variable]
_Expr = _Node
_Target = Union[str, NamedNode, DefaultGraph]

@final
class SelectBuilder:
    """Builds a SELECT query."""

    def __new__(cls) -> SelectBuilder: ...
    def prefix(self, prefix: str, iri: str) -> SelectBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> SelectBuilder: ...
    def base(self, iri: str) -> SelectBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> SelectBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> SelectBuilder: ...
    def add_where(self, w: WhereBuilder) -> SelectBuilder: ...
    def group(self, w: WhereBuilder) -> SelectBuilder: ...
    def optional(self, w: WhereBuilder) -> SelectBuilder: ...
    def union(self, *branches: WhereBuilder) -> SelectBuilder: ...
    def minus(self, w: WhereBuilder) -> SelectBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> SelectBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> SelectBuilder: ...
    def filter(self, e: _Expr) -> SelectBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> SelectBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> SelectBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> SelectBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> SelectBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> SelectBuilder: ...
    def sub_select(self, q: SelectBuilder) -> SelectBuilder: ...
    def order_by(self, e: _Expr) -> SelectBuilder: ...
    def order_by_desc(self, e: _Expr) -> SelectBuilder: ...
    def limit(self, n: int) -> SelectBuilder: ...
    def offset(self, n: int) -> SelectBuilder: ...
    def from_(self, g: _Node) -> SelectBuilder: ...
    def from_named(self, g: _Node) -> SelectBuilder: ...
    def select(self, *vars: _Node) -> SelectBuilder: ...
    def select_expr(self, e: _Expr, alias: _Node) -> SelectBuilder: ...
    def select_all(self) -> SelectBuilder: ...
    def distinct(self) -> SelectBuilder: ...
    def reduced(self) -> SelectBuilder: ...
    def group_by(self, e: _Expr, alias: _Node | None = None) -> SelectBuilder: ...
    def having(self, e: _Expr) -> SelectBuilder: ...

@final
class AskBuilder:
    """Builds an ASK query."""

    def __new__(cls) -> AskBuilder: ...
    def prefix(self, prefix: str, iri: str) -> AskBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> AskBuilder: ...
    def base(self, iri: str) -> AskBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> AskBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> AskBuilder: ...
    def add_where(self, w: WhereBuilder) -> AskBuilder: ...
    def group(self, w: WhereBuilder) -> AskBuilder: ...
    def optional(self, w: WhereBuilder) -> AskBuilder: ...
    def union(self, *branches: WhereBuilder) -> AskBuilder: ...
    def minus(self, w: WhereBuilder) -> AskBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> AskBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> AskBuilder: ...
    def filter(self, e: _Expr) -> AskBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> AskBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> AskBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> AskBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> AskBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> AskBuilder: ...
    def sub_select(self, q: SelectBuilder) -> AskBuilder: ...
    def from_(self, g: _Node) -> AskBuilder: ...
    def from_named(self, g: _Node) -> AskBuilder: ...

@final
class ConstructBuilder:
    """Builds a CONSTRUCT query."""

    def __new__(cls) -> ConstructBuilder: ...
    def prefix(self, prefix: str, iri: str) -> ConstructBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> ConstructBuilder: ...
    def base(self, iri: str) -> ConstructBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> ConstructBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> ConstructBuilder: ...
    def add_where(self, w: WhereBuilder) -> ConstructBuilder: ...
    def group(self, w: WhereBuilder) -> ConstructBuilder: ...
    def optional(self, w: WhereBuilder) -> ConstructBuilder: ...
    def union(self, *branches: WhereBuilder) -> ConstructBuilder: ...
    def minus(self, w: WhereBuilder) -> ConstructBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> ConstructBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> ConstructBuilder: ...
    def filter(self, e: _Expr) -> ConstructBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> ConstructBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> ConstructBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> ConstructBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> ConstructBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> ConstructBuilder: ...
    def sub_select(self, q: SelectBuilder) -> ConstructBuilder: ...
    def order_by(self, e: _Expr) -> ConstructBuilder: ...
    def order_by_desc(self, e: _Expr) -> ConstructBuilder: ...
    def limit(self, n: int) -> ConstructBuilder: ...
    def offset(self, n: int) -> ConstructBuilder: ...
    def from_(self, g: _Node) -> ConstructBuilder: ...
    def from_named(self, g: _Node) -> ConstructBuilder: ...
    def construct(self, s: _Node, p: _Node, o: _Node) -> ConstructBuilder: ...

@final
class DescribeBuilder:
    """Builds a DESCRIBE query."""

    def __new__(cls) -> DescribeBuilder: ...
    def prefix(self, prefix: str, iri: str) -> DescribeBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> DescribeBuilder: ...
    def base(self, iri: str) -> DescribeBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> DescribeBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> DescribeBuilder: ...
    def add_where(self, w: WhereBuilder) -> DescribeBuilder: ...
    def group(self, w: WhereBuilder) -> DescribeBuilder: ...
    def optional(self, w: WhereBuilder) -> DescribeBuilder: ...
    def union(self, *branches: WhereBuilder) -> DescribeBuilder: ...
    def minus(self, w: WhereBuilder) -> DescribeBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> DescribeBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> DescribeBuilder: ...
    def filter(self, e: _Expr) -> DescribeBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> DescribeBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> DescribeBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> DescribeBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> DescribeBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> DescribeBuilder: ...
    def sub_select(self, q: SelectBuilder) -> DescribeBuilder: ...
    def order_by(self, e: _Expr) -> DescribeBuilder: ...
    def order_by_desc(self, e: _Expr) -> DescribeBuilder: ...
    def limit(self, n: int) -> DescribeBuilder: ...
    def offset(self, n: int) -> DescribeBuilder: ...
    def from_(self, g: _Node) -> DescribeBuilder: ...
    def from_named(self, g: _Node) -> DescribeBuilder: ...
    def describe(self, *resources: _Node) -> DescribeBuilder: ...

@final
class UpdateBuilder:
    """Builds a SPARQL Update request."""

    def __new__(cls) -> UpdateBuilder: ...
    def prefix(self, prefix: str, iri: str) -> UpdateBuilder: ...
    def prefixes(self, prefixes: dict[str, str]) -> UpdateBuilder: ...
    def base(self, iri: str) -> UpdateBuilder: ...
    def set_var(self, var: _Node, value: _Node) -> UpdateBuilder: ...
    def build(self) -> str: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> UpdateBuilder: ...
    def add_where(self, w: WhereBuilder) -> UpdateBuilder: ...
    def group(self, w: WhereBuilder) -> UpdateBuilder: ...
    def optional(self, w: WhereBuilder) -> UpdateBuilder: ...
    def union(self, *branches: WhereBuilder) -> UpdateBuilder: ...
    def minus(self, w: WhereBuilder) -> UpdateBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> UpdateBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> UpdateBuilder: ...
    def filter(self, e: _Expr) -> UpdateBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> UpdateBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> UpdateBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> UpdateBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> UpdateBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> UpdateBuilder: ...
    def sub_select(self, q: SelectBuilder) -> UpdateBuilder: ...
    def then(self) -> UpdateBuilder: ...
    def insert_data(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete_data(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete_where(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def delete(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def insert(self, s: _Node, p: _Node, o: _Node, *, graph: _Node | None = None) -> UpdateBuilder: ...
    def with_(self, g: _Node) -> UpdateBuilder: ...
    def using(self, g: _Node) -> UpdateBuilder: ...
    def using_named(self, g: _Node) -> UpdateBuilder: ...
    def load(self, source: _Node, *, into: _Node | None = None) -> UpdateBuilder: ...
    def clear(self, target_: _Target) -> UpdateBuilder: ...
    def drop(self, target_: _Target) -> UpdateBuilder: ...
    def create(self, g: _Node) -> UpdateBuilder: ...
    def add(self, source: _Target, to: _Target) -> UpdateBuilder: ...
    def copy(self, source: _Target, to: _Target) -> UpdateBuilder: ...
    def move_(self, source: _Target, to: _Target) -> UpdateBuilder: ...

@final
class WhereBuilder:
    """A group of patterns for the nested patterns of a builder."""

    def __new__(cls) -> WhereBuilder: ...
    def where_(self, s: _Node, p: _Node, o: _Node) -> WhereBuilder: ...
    def add_where(self, w: WhereBuilder) -> WhereBuilder: ...
    def group(self, w: WhereBuilder) -> WhereBuilder: ...
    def optional(self, w: WhereBuilder) -> WhereBuilder: ...
    def union(self, *branches: WhereBuilder) -> WhereBuilder: ...
    def minus(self, w: WhereBuilder) -> WhereBuilder: ...
    def graph(self, g: _Node, w: WhereBuilder) -> WhereBuilder: ...
    def service(self, endpoint: _Node, w: WhereBuilder, *, silent: bool = False) -> WhereBuilder: ...
    def filter(self, e: _Expr) -> WhereBuilder: ...
    def filter_exists(self, w: WhereBuilder) -> WhereBuilder: ...
    def filter_not_exists(self, w: WhereBuilder) -> WhereBuilder: ...
    def bind(self, e: _Expr, var: _Node) -> WhereBuilder: ...
    def values(self, var: _Node, values: Iterable[_Node]) -> WhereBuilder: ...
    def values_rows(self, vars: Iterable[_Node], rows: Iterable[Iterable[_Node | None]]) -> WhereBuilder: ...
    def sub_select(self, q: SelectBuilder) -> WhereBuilder: ...

@final
class Schema:
    def report(self, /, *, graph: str = ..., declared_graph: str | None = None, include_inferred: bool = True, at: int | str | None = None, limit: int = 1000, cursor: str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def classes(self, /, *, graph: str = ..., declared_graph: str | None = None, include_inferred: bool = True, at: int | str | None = None, limit: int = 1000, cursor: str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def predicates(self, /, *, graph: str = ..., declared_graph: str | None = None, include_inferred: bool = True, at: int | str | None = None, limit: int = 1000, cursor: str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def diff(self, /, from_commit: int | str, to_commit: int | str | None = None, *, graph: str = ..., declared_graph: str | None = None, include_inferred: bool = True, limit: int = 1000, cursor: str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def profiles(self, /, *, classes: Iterable[str] | None = None, graph: str = ..., include_inferred: bool = True, at: int | str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def draft_shapes(self, /, *, format: str = "turtle", classes: Iterable[str] | None = None, support: float = 1.0, min_instances: int = 1, max_in: int = 20, max_count: int = 10, closed: bool = False, base: str | None = None, graph: str = ..., include_inferred: bool = True, at: int | str | None = None, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> str | dict[str, Any]: ...
    def void(self, /, *, graph: str = ..., include_inferred: bool = True, at: int | str | None = None, declarations: bool = True, max_entries: int = 100000, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> str: ...
    def constraints(self, /, *, shapes: Iterable[str] | None = None, at: int | str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...

@final
class Validation:
    def shacl(self, /, shapes: str | bytes | None = None, *, format: _Format | None = None, shapes_graph: NamedNode | str | None = None, data_graph: NamedNode | str | None = None, include_inferred: bool = False, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> ShaclReport: ...
    def shex(self, /, schema: str, shape_map: str, *, format: str | None = None, data_graph: NamedNode | str | None = None, include_inferred: bool = False, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> ShexReport: ...
    @property
    def guard(self) -> GuardSetting: ...

@final
class GuardSetting:
    def get(self, /) -> dict[str, Any] | None: ...
    def reset(self, /) -> None: ...
    def set(self, /, config: Mapping[str, Any]) -> dict[str, Any]: ...

@final
class Branches:
    def relink(self, /, name: str, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def list(self, /) -> builtins.list[dict[str, Any]]: ...
    def get(self, /, name: str) -> dict[str, Any]: ...
    def create(self, /, name: str, *, from_branch: str = ..., at: int | str | None = None, protected: bool = False, note: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def update(self, /, name: str, *, protected: bool | None = None, note: str | None = None, new_name: str | None = None) -> dict[str, Any]: ...
    def delete(self, /, name: str, *, force: bool = False, reparent: bool = False) -> None: ...
    def commit_graph(self, /, *, branches: Iterable[str] | None = None, before: str | None = None, limit: int = 100) -> dict[str, Any]: ...
    def merge(self, /, source: str, target: str = ..., *, ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def preview_merge(self, /, source: str, target: str = ..., *, ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def revert(self, /, commit: int, *, branch: str = ..., ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def preview_revert(self, /, commit: int, *, branch: str = ..., ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def cherry_pick(self, /, source: str, commit: int, target: str = ..., *, ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def preview_cherry_pick(self, /, source: str, commit: int, target: str = ..., *, ff_only: bool = False, squash: bool = False, replay: bool = False, scope: str = "cell", on_conflict: str | None = None, resolutions: Iterable[Mapping[str, Any]] | None = None, exempt: Iterable[NamedNode] | None = None, expect_source: int | None = None, expect_target: int | None = None, include_inferences: bool = False, max_quads: int = 0, limit: int = 100, message: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    @property
    def settings(self) -> BranchSettings: ...

@final
class BranchSettings:
    def get(self, /) -> builtins.list[str]: ...
    def set(self, /, predicates: Iterable[NamedNode] | None) -> builtins.list[str]: ...
    def reset(self, /) -> builtins.list[str]: ...

@final
class Backup:
    def to_dict(self, /) -> dict[str, Any]: ...
    @property
    def logical_bytes(self) -> int: ...
    @property
    def commit(self) -> int: ...
    @property
    def repository(self) -> str: ...
    @property
    def completed(self) -> str: ...
    @property
    def added_bytes(self) -> int: ...
    @property
    def dataset_id(self) -> str: ...
    @property
    def dataset_name(self) -> str: ...
    @property
    def quads(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def note(self) -> str | None: ...
    @property
    def created(self) -> str: ...

@final
class BackupRepository:
    @staticmethod
    def open(url_or_config: str | Mapping[str, Any], *, cache_dir: _Path | None = None, init: bool = True) -> BackupRepository: ...
    def test(self, /) -> dict[str, Any]: ...
    def stats(self, /) -> dict[str, Any]: ...
    def backups(self, /, *, dataset: str | None = None, policy: str | None = None, limit: int | None = None, before: str | None = None) -> builtins.list[Backup]: ...
    def verify(self, /, names: Iterable[str] | None = None, *, level: str = "exists", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def gc(self, /, *, dry_run: bool = False, grace: float = 86400.0, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def locks(self, /) -> builtins.list[dict[str, Any]]: ...
    def break_lock(self, /, id: str) -> bool: ...
    @property
    def id(self) -> str: ...

@final
class Backups:
    def create(self, /, name: str | None = None, *, note: str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> Backup: ...
    def list(self, /, *, policy: str | None = None, limit: int | None = None, before: str | None = None) -> builtins.list[Backup]: ...
    def get(self, /, name: str) -> dict[str, Any] | None: ...
    def delete(self, /, name: str) -> bool: ...
    def verify(self, /, name: str, *, level: str = "exists", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def restore_to_dir(self, /, name: str, directory: _Path, *, identity: str = "auto", check: str = "quick", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def run_policy(self, /, policy: Mapping[str, Any], *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...

@final
class Repositories:
    def list(self, /) -> builtins.list[dict[str, Any]]: ...
    def get(self, /, name: str) -> dict[str, Any] | None: ...
    def add(self, /, config: Mapping[str, Any]) -> dict[str, Any]: ...
    def update(self, /, name: str, config: Mapping[str, Any]) -> dict[str, Any]: ...
    def remove(self, /, name: str) -> bool: ...
    def open(self, /, name: str) -> BackupRepository: ...
    def with_fixed(self, /, entries: Iterable[Mapping[str, Any]]) -> builtins.list[dict[str, Any]]: ...

@final
class Catalog:
    def __new__(cls, path: _Path, *, union_default_graph: bool = False) -> Catalog: ...
    def __getitem__(self, key: str, /) -> Dataset: ...
    @staticmethod
    def memory(*, union_default_graph: bool = False) -> Catalog: ...
    @staticmethod
    def inspect(path: _Path) -> builtins.list[DatasetInfo]: ...
    def list(self, /) -> builtins.list[DatasetInfo]: ...
    def info(self, /, name: str) -> DatasetInfo | None: ...
    def get(self, /, name: str) -> Dataset | None: ...
    def get_by_id(self, /, id: str) -> Dataset | None: ...
    def create(self, /, name: str, *, kind: str = "persistent", geo: Mapping[str, Any] | None = None) -> Dataset: ...
    def attach(self, /, name: str, path: _Path | None = None) -> Dataset: ...
    def delete(self, /, name: str) -> bool: ...
    def rename(self, /, name: str, new_name: str) -> Dataset: ...
    def clone_dataset(self, /, source: str, name: str, *, kind: str | None = None, at: int | str | None = None, inferences: str = "copy", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> Dataset: ...
    def backup_files(self, /) -> builtins.list[dict[str, Any]]: ...
    def close(self, /) -> None: ...
    def __enter__(self, /) -> Catalog: ...
    def __exit__(self, /, _ty: type[BaseException] | None, _value: BaseException | None, _traceback: TracebackType | None) -> bool: ...
    def restore(self, /, repository: BackupRepository, backup: str, *, name: str, identity: str = "auto", in_place: bool = False, check: str = "quick", cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> Dataset: ...
    def run_policy(self, /, policy: Mapping[str, Any], *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def apply_retention(self, /, policy: Mapping[str, Any], *, dry_run: bool = False) -> dict[str, Any]: ...
    def reserve(self, /, name: str, *, kind: str = "clone", holder: str = "python") -> Reservation: ...
    @property
    def repositories(self) -> Repositories: ...

@final
class Reservation:
    def close(self, /) -> None: ...
    def __enter__(self, /) -> Reservation: ...
    def __exit__(self, /, _ty: type[BaseException] | None, _value: BaseException | None, _tb: TracebackType | None) -> bool: ...
    @property
    def name(self) -> str: ...

@final
class DatasetInfo:
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def reserved_by(self) -> str | None: ...
    @property
    def attached(self) -> bool: ...
    @property
    def id(self) -> str: ...
    @property
    def path(self) -> str | None: ...

@final
class Snapshots:
    def list(self, /) -> builtins.list[Snapshot]: ...
    def get(self, /, name: str) -> Snapshot | None: ...
    def create(self, /, name: str, *, at: int | str | None = None, note: str | None = None, expires_ms: int | None = None) -> Snapshot: ...
    def delete(self, /, name: str) -> bool: ...

@final
class History:
    def status(self, /) -> dict[str, Any]: ...
    def commit(self, /, reference: int | str) -> Commit | None: ...
    def commits(self, /, limit: int = 100, *, before: int | None = None, after: int | None = None) -> builtins.list[Commit]: ...
    def diff(self, /, from_commit: int | str, to_commit: int | str | None = None, *, graph: str | None = None, max_quads: int = 0, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> Diff: ...
    def changes(self, /, after: int, *, max_commits: int = 100, max_quads: int = 0, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> ChangePage: ...
    def wait_for_commit(self, /, after: int, *, timeout: float | None = 30.0, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None) -> int | None: ...
    def prune(self, /) -> int: ...
    def tick(self, /) -> dict[str, Any]: ...
    def query(self, /, *, subjects: Iterable[_Term] | None = None, predicates: Iterable[NamedNode] | None = None, objects: Iterable[_Term] | None = None, graphs: Iterable[_GraphName | str] | None = None, from_commit: int | str | None = None, to_commit: int | str | None = None, op: str | None = None, limit: int = 0, descending: bool = False, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...

@final
class Settings:
    @property
    def compaction(self) -> CompactionSetting: ...
    @property
    def describe(self) -> DescribeSetting: ...
    @property
    def retention(self) -> RetentionSetting: ...
    @property
    def change_log(self) -> ChangeLogSetting: ...
    @property
    def quota(self) -> QuotaSetting: ...

@final
class CompactionSetting:
    def get(self, /) -> dict[str, Any]: ...
    def reset(self, /) -> dict[str, Any]: ...
    def set(self, /, config: Mapping[str, Any]) -> None: ...
    def status(self, /) -> dict[str, Any]: ...

@final
class DescribeSetting:
    def get(self, /) -> dict[str, Any]: ...
    def reset(self, /) -> dict[str, Any]: ...
    def set(self, /, config: _Describe) -> None: ...

@final
class QuotaSetting:
    def get(self, /) -> dict[str, Any]: ...
    def reset(self, /) -> dict[str, Any]: ...
    def set(self, /, *, max_bytes: int) -> dict[str, Any]: ...

@final
class RetentionSetting:
    def get(self, /) -> dict[str, Any]: ...
    def reset(self, /) -> dict[str, Any]: ...
    def set(self, /, config: Mapping[str, Any] | None = None, *, keep_commits: int | None = None, keep_age: float | None = None, max_bytes: int | None = None, schedules: Mapping[str, Any] | None = None, catalog: Mapping[str, Any] | None = None) -> dict[str, Any]: ...

@final
class ChangeLogSetting:
    def get(self, /) -> dict[str, Any]: ...
    def reset(self, /) -> dict[str, Any]: ...
    def set(self, /, config: Mapping[str, Any]) -> None: ...
    def status(self, /) -> dict[str, Any]: ...

@final
class Diff:
    def __iter__(self, /) -> Iterator[tuple[str, Quad]]: ...
    def __len__(self, /) -> int: ...
    @property
    def removed(self) -> int: ...
    @property
    def from_commit(self) -> int: ...
    @property
    def method(self) -> str: ...
    @property
    def added(self) -> int: ...
    @property
    def to_commit(self) -> int: ...

@final
class CommitChanges:
    @property
    def commit(self) -> Commit: ...
    def __iter__(self, /) -> Iterator[tuple[str, Quad]]: ...
    @property
    def added(self) -> int: ...
    @property
    def complete(self) -> bool: ...
    @property
    def removed(self) -> int: ...

@final
class ChangePage:
    @property
    def head(self) -> Commit: ...
    def __iter__(self, /) -> Iterator[CommitChanges]: ...
    @property
    def next(self) -> int: ...
    @property
    def after(self) -> int: ...
    @property
    def commits(self) -> tuple[CommitChanges, ...]: ...

@final
class HistoryChange:
    @property
    def seq(self) -> int: ...
    @property
    def quad(self) -> Quad: ...
    @property
    def op(self) -> str: ...

@final
class GraphQL:
    def versions(self, /) -> builtins.list[dict[str, Any]]: ...
    def sdl(self, /) -> str | None: ...
    def execute(self, /, query: str, variables: Mapping[str, Any] | None = None, operation_name: str | None = None, *, at: int | str | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def draft(self, /, *, source: str | None = None, shapes_graph: str | None = None, graph: str = "default", support: float = 1.0, classes: Iterable[str] | None = None, min_instances: int = 1, include_inferred: bool = False, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = 600.0) -> dict[str, Any]: ...
    @property
    def config(self) -> GraphQLConfig: ...

@final
class GraphQLConfig:
    def get(self, /, *, version: int | None = None) -> dict[str, Any] | None: ...
    def set(self, /, config: Mapping[str, Any], *, author: str | None = None, message: str | None = None, if_version: int | None = None) -> dict[str, Any]: ...
    def reset(self, /, *, if_version: int | None = None) -> bool: ...

@final
class Indexes:
    @property
    def vector(self) -> VectorIndexes: ...
    @property
    def text(self) -> TextIndex: ...
    @property
    def geo(self) -> GeoIndex: ...

@final
class TextIndex:
    def status(self, /) -> dict[str, Any] | None: ...
    def enabled(self, /) -> bool: ...
    def enable(self, /, config: Mapping[str, Any] | None = None, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def disable(self, /) -> None: ...
    def rebuild(self, /, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def search(self, /, query: str, *, predicates: Iterable[NamedNode] | None = None, lang: str | None = None, graph: str | None = None, limit: int = 20, highlight: bool = True, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...

@final
class VectorIndexes:
    def list(self, /) -> builtins.list[dict[str, Any]]: ...
    def get(self, /, name: str) -> dict[str, Any] | None: ...
    def put(self, /, name: str, config: Mapping[str, Any], *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> bool: ...
    def drop(self, /, name: str) -> None: ...
    def rebuild(self, /, name: str) -> None: ...
    def reembed(self, /, name: str) -> None: ...
    def embedding_status(self, /, name: str) -> dict[str, Any] | None: ...
    def wait(self, /, name: str, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def recall(self, /, name: str, *, samples: int = 100, k: int = 10, ef: int | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def embed_until_idle(self, /, *, timeout: float | None = 3600.0, allow_private: bool = True, secrets: Mapping[str, str] | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None) -> None: ...

@final
class GeoIndex:
    def status(self, /) -> dict[str, Any] | None: ...
    def enabled(self, /) -> bool: ...
    def enable(self, /, config: Mapping[str, Any]) -> dict[str, Any]: ...
    def disable(self, /) -> None: ...
    def rebuild(self, /) -> None: ...
    def wait(self, /, *, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    def features(self, /, *, bbox: tuple[float, float, float, float], limit: int = 1000, graph: str | None = None, predicate: NamedNode | None = None, tolerance: float | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...

@final
class Reasoning:
    def status(self, /) -> dict[str, Any] | None: ...
    def run(self, /, profile: Any = "rdfs", *, rules: str | None = None, inputs: Mapping[str, Any] | None = None, incremental: bool = True, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> ReasonReport: ...
    def clear(self, /) -> int: ...
    def diagnostics(self, /, *, checks: Iterable[str] | None = None, limit: int = 100, include_inferred: bool = False, graphs: Iterable[str] | None = None, cancel: CancelToken | None = None, progress: Callable[[float, str], None] | None = None, timeout: float | None = None) -> dict[str, Any]: ...
    @property
    def rdfs(self) -> RdfsSetting: ...

@final
class RdfsSetting:
    def get(self, /) -> dict[str, Any] | None: ...
    def set(self, /, schema: str | bytes | None = None, *, graph: str | None = None, format: _Format | None = None) -> None: ...
    def reset(self, /) -> None: ...

@final
class StoredQueries:
    def list(self, /) -> builtins.list[dict[str, Any]]: ...
    def get(self, /, name: str, *, version: int | None = None) -> dict[str, Any] | None: ...
    def versions(self, /, name: str) -> builtins.list[dict[str, Any]]: ...
    def put(self, /, name: str, query: str, *, parameters: Mapping[str, Mapping[str, Any]] | None = None, description: str | None = None, results: str | None = None, mcp: bool = True, author: str | None = None, message: str | None = None, if_version: int | None = None) -> dict[str, Any]: ...
    def delete(self, /, name: str, *, if_version: int | None = None) -> bool: ...
    def run(self, /, name: str, params: Mapping[str, Any] | None = None, *, version: int | None = None, progress: Callable[[float, str], None] | None = None, **query_kwargs: Any) -> _QueryResult: ...

def check_iri(iri: str) -> dict[str, Any]: ...

def check_langtag(tag: str) -> dict[str, Any]: ...

def check_data(text: str, format: _Format | None, *, base_iri: str | None = None) -> dict[str, Any]: ...

def parse_query(query: str, *, base_iri: str | None = None, prefixes: Mapping[str, str] | None = None) -> str: ...

def parse_update(update: str, *, base_iri: str | None = None, prefixes: Mapping[str, str] | None = None) -> str: ...

def convert_geometries(items: Iterable[Mapping[str, Any]]) -> builtins.list[dict[str, Any]]: ...

def preview_schedule(schedule: str, timezone: str = "UTC", n: int = 5, *, after: int | None = None) -> builtins.list[str]: ...
