//! The vocabulary of spec C18 §8.10.3 and its shapes. `sparkles memory init` writes the
//! vocabulary into [`VOCAB_GRAPH`] and the shapes into [`SHAPES_GRAPH`], so that
//! `assert_facts` knows every term an import uses.

/// The namespace `mem:`.
pub const MEM: &str = "urn:x-sparkles:mem:";
/// The graph of the vocabulary.
pub const VOCAB_GRAPH: &str = "urn:x-sparkles:vocab:mem";
/// The graph of the memory shapes that `init` adds to the guard.
pub const SHAPES_GRAPH: &str = "urn:x-sparkles:shapes:mem";

pub const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
pub const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
pub const SCHEMA_DESCRIPTION: &str = "http://schema.org/description";
pub const DCT_MODIFIED: &str = "http://purl.org/dc/terms/modified";
pub const DCT_REFERENCES: &str = "http://purl.org/dc/terms/references";
pub const DCT_REPLACES: &str = "http://purl.org/dc/terms/replaces";
pub const DCT_TITLE: &str = "http://purl.org/dc/terms/title";
pub const DCT_FORMAT: &str = "http://purl.org/dc/terms/format";
pub const PROV_ENTITY: &str = "http://www.w3.org/ns/prov#Entity";
pub const PROV_INVALIDATED_AT: &str = "http://www.w3.org/ns/prov#invalidatedAtTime";
pub const PROV_STARTED_AT: &str = "http://www.w3.org/ns/prov#startedAtTime";
pub const PROV_ENDED_AT: &str = "http://www.w3.org/ns/prov#endedAtTime";
pub const PROV_GENERATED_BY: &str = "http://www.w3.org/ns/prov#wasGeneratedBy";
pub const SPK_CONTENT_DIGEST: &str = "urn:x-sparkles:contentDigest";
pub const XSD_DATETIME: &str = "http://www.w3.org/2001/XMLSchema#dateTime";
pub const XSD_INTEGER: &str = "http://www.w3.org/2001/XMLSchema#integer";
pub const XSD_BOOLEAN: &str = "http://www.w3.org/2001/XMLSchema#boolean";

/// A term of `mem:`.
pub fn mem(local: &str) -> String {
    format!("{MEM}{local}")
}

/// The predicates whose values the import states exactly. A re-import replaces their
/// values with `mode: "replace"` and retracts the others it no longer states.
pub fn single_valued(p: &str) -> bool {
    [
        RDFS_LABEL,
        SCHEMA_DESCRIPTION,
        DCT_MODIFIED,
        DCT_TITLE,
        DCT_FORMAT,
        SPK_CONTENT_DIGEST,
        PROV_STARTED_AT,
        PROV_ENDED_AT,
    ]
    .contains(&p)
        || p.strip_prefix(MEM).is_some_and(|l| {
            matches!(
                l,
                "sessionId"
                    | "gitBranch"
                    | "model"
                    | "harnessVersion"
                    | "kind"
                    | "harness"
                    | "project"
                    | "scope"
                    | "alwaysApply"
                    | "filePath"
                    | "file"
                    | "indexPosition"
                    | "indexText"
                    | "redactions"
            )
        })
}

/// Every predicate the import writes. A sync reads back only facts with these
/// predicates, so the facts an agent extracts from the same file are left alone.
pub fn structural(p: &str) -> bool {
    single_valued(p)
        || [
            RDF_TYPE,
            DCT_REFERENCES,
            DCT_REPLACES,
            PROV_INVALIDATED_AT,
            PROV_GENERATED_BY,
        ]
        .contains(&p)
        || p.strip_prefix(MEM)
            .is_some_and(|l| matches!(l, "appliesTo" | "imports" | "copyOf"))
}

/// The vocabulary graph in Turtle. Standard terms the import uses are declared too, so a
/// new dataset knows them before its first import.
pub const VOCAB_TTL: &str = r#"@prefix mem:     <urn:x-sparkles:mem:> .
@prefix spk:     <urn:x-sparkles:> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:     <http://www.w3.org/2002/07/owl#> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix schema:  <http://schema.org/> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .

mem:Memory a rdfs:Class ; rdfs:subClassOf prov:Entity ;
    rdfs:label "Memory" ; rdfs:comment "One memory of a coding agent, such as one Claude Code memory file." .
mem:UserMemory a rdfs:Class ; rdfs:subClassOf mem:Memory ; rdfs:label "User memory" .
mem:FeedbackMemory a rdfs:Class ; rdfs:subClassOf mem:Memory ; rdfs:label "Feedback memory" .
mem:ProjectMemory a rdfs:Class ; rdfs:subClassOf mem:Memory ; rdfs:label "Project memory" .
mem:ReferenceMemory a rdfs:Class ; rdfs:subClassOf mem:Memory ; rdfs:label "Reference memory" .
mem:GeneratedMemory a rdfs:Class ; rdfs:subClassOf mem:Memory ;
    rdfs:label "Generated memory" ; rdfs:comment "A memory that a harness generated by itself, such as Codex's." .
mem:Instructions a rdfs:Class ; rdfs:subClassOf prov:Entity ;
    rdfs:label "Instructions" ; rdfs:comment "An instruction file such as CLAUDE.md, AGENTS.md, GEMINI.md or a rule." .
mem:Project a rdfs:Class ; rdfs:label "Project" ;
    rdfs:comment "A repository or directory that memories belong to." .
mem:Session a rdfs:Class ; rdfs:subClassOf prov:Activity ; rdfs:label "Session" .
mem:Harness a rdfs:Class ; rdfs:subClassOf prov:SoftwareAgent ; rdfs:label "Harness" .
mem:Scope a rdfs:Class ; rdfs:label "Scope of an instruction file" .
prov:Entity a rdfs:Class .

mem:ClaudeCode a mem:Harness ; rdfs:label "Claude Code" .
mem:Codex a mem:Harness ; rdfs:label "Codex" .
mem:GeminiCli a mem:Harness ; rdfs:label "Gemini CLI" .
mem:Cursor a mem:Harness ; rdfs:label "Cursor" .
mem:Generic a mem:Harness ; rdfs:label "Generic" .

mem:UserScope a mem:Scope ; rdfs:label "user" .
mem:ProjectScope a mem:Scope ; rdfs:label "project" .
mem:LocalScope a mem:Scope ; rdfs:label "local" .
mem:RuleScope a mem:Scope ; rdfs:label "rule" .
mem:ManagedScope a mem:Scope ; rdfs:label "managed" .

mem:kind a rdf:Property ; rdfs:label "kind" ; rdfs:range xsd:string ;
    rdfs:comment "The kind exactly as the file states it." .
mem:harness a rdf:Property ; rdfs:label "harness" ; rdfs:range mem:Harness .
mem:project a rdf:Property ; rdfs:label "project" ; rdfs:range mem:Project .
mem:scope a rdf:Property ; rdfs:label "scope" ; rdfs:range mem:Scope .
mem:appliesTo a rdf:Property ; rdfs:label "applies to" ; rdfs:range xsd:string .
mem:alwaysApply a rdf:Property ; rdfs:label "always apply" ; rdfs:range xsd:boolean .
mem:filePath a rdf:Property ; rdfs:label "file path" ; rdfs:range xsd:string .
mem:file a rdf:Property ; rdfs:label "file" ; rdfs:range prov:Entity .
mem:indexPosition a rdf:Property ; rdfs:label "index position" ; rdfs:range xsd:integer .
mem:indexText a rdf:Property ; rdfs:label "index text" ; rdfs:range xsd:string .
mem:imports a rdf:Property ; rdfs:label "imports" .
mem:copyOf a rdf:Property ; rdfs:label "copy of" .
mem:sessionId a rdf:Property ; rdfs:label "session id" .
mem:gitBranch a rdf:Property ; rdfs:label "git branch" .
mem:model a rdf:Property ; rdfs:label "model" .
mem:harnessVersion a rdf:Property ; rdfs:label "harness version" .
mem:redactions a rdf:Property ; rdfs:label "redactions" ; rdfs:range xsd:integer .

rdfs:label a rdf:Property .
schema:description a rdf:Property .
dcterms:modified a rdf:Property .
dcterms:references a rdf:Property .
dcterms:replaces a rdf:Property .
dcterms:title a rdf:Property .
dcterms:format a rdf:Property .
spk:contentDigest a rdf:Property .
prov:invalidatedAtTime a rdf:Property .
prov:startedAtTime a rdf:Property .
prov:endedAtTime a rdf:Property .
prov:wasGeneratedBy a rdf:Property .
"#;

/// The shapes of §8.10.3: one value of each single-valued property of a memory.
pub const SHAPES_TTL: &str = r#"@prefix mem:     <urn:x-sparkles:mem:> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix schema:  <http://schema.org/> .

mem:MemoryShape a sh:NodeShape ;
    sh:targetClass mem:Memory ;
    sh:property [ sh:path rdfs:label ; sh:maxCount 1 ] ,
                [ sh:path schema:description ; sh:maxCount 1 ] ,
                [ sh:path dcterms:modified ; sh:maxCount 1 ] ,
                [ sh:path mem:kind ; sh:maxCount 1 ] ,
                [ sh:path mem:filePath ; sh:maxCount 1 ] ,
                [ sh:path mem:indexPosition ; sh:maxCount 1 ] ,
                [ sh:path mem:file ; sh:maxCount 1 ] .
"#;
