PREFIX ex: <http://example.org/>

SELECT *
WHERE {
  ?s ex:p ?o .
  SEMIJOIN {
    ?s ex:q ?z .
  }
  ANTIJOIN {
    ?s ex:r ?r .
  }
  ?s distinct(ex:n/ex:n) ?a .
  ?a multi(ex:n*) ?b .
  ?b ex:m/distinct(ex:n|ex:m)+ ?c .
  ?c ex:n^ex:m ?d .
}
