PREFIX ex: <http://example.org/>


# --- Vocabularies ---


# (a second block)

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# --- The query ---

SELECT ?s
WHERE {
  ?s rdfs:label ?l .
}
