PREFIX schema: <https://schema.org/>

SELECT ?s
WHERE {
  ?s schema:price ?price ;
    schema:priceCurrency ?currency .
  FILTER(
    ?price > "10"^^<http://www.w3.org/2001/XMLSchema#decimal>
      && ?price < 1000
      && CONTAINS(LCASE(STR(?s)), "sale")
      && ?currency != "GBP"
  )
  FILTER(
    ?currency = "EUR"
      || (?currency = "USD" && ?price < 500 && ?price > 100 && BOUND(?s) && !isBLANK(?s))
      || ?currency = "CHF"
  )
  FILTER(LANG(?s) = "en" || LANG(?s) = "")
}
