VERSION '1.2'
PREFIX : <http://example.org/>
PREFIX ex: <http://example.org/ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
BASE <http://example.org/base/>
PREFIX abs: <http://a/>
PREFIX rel: <rel/>

SELECT *
WHERE {
  ?s ?p ?o .
}
