PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
SELECT * WHERE {
  # sparkles-fmt: ignore
  ?s   rdf:type   <http://example.org/Thing> .
  ?s ?p "1"^^xsd:integer .
}
