PREFIX ex: <http://example.org/> # our vocabulary
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?name ?mbox
WHERE {
  # people only
  ?p a foaf:Person ;
    foaf:name ?name .
  OPTIONAL {
    ?p foaf:mbox ?mbox .
  }
  {
    ?p ex:role ex:Admin .
  } UNION {
    ?p ex:role ex:Owner .
  }
  FILTER(LANG(?name) = "en" || LANG(?name) = "") # English or untagged
}
ORDER BY ?name
LIMIT 10
